### ISSUE TITLE
Filter services by mock url

### ISSUE THREAD

**Issue by fernandospr** [clafonta/Mockey#102]
Oftentimes I cannot find the service I've already created.
I know the url, but cannot recall the service name. So, I have to go service by service until I find it.

**Comment by clafonta** [comment]
Fixed. Let me know if this doesn't work for you and then I can re-open.

**Comment by fernandospr** [comment]
Thanks, but on which branch did you fix it?

**Comment by clafonta** [comment]
Hmm - not sure what happened. I'll publish an update later this weekend.

**Comment by clafonta** [comment]
Fixed - in master.
