### ISSUE TITLE
Returns response of some other scenario if requested url matches part of some other scenario url

### ISSUE THREAD

**Issue by A-MohanRao** [clafonta/Mockey#109]
Assume the following scenario created in Mockey.

Service#1, Scenario#1
http://127.0.0.1:8090/Mockey/service/api/v1/cxtid/{contextId}/cid/{customerId}/feature/somefunctionality

Service#2, Scenario#1
http://127.0.0.1:8090/Mockey/service/api/v1/cxtid/{contextId}/cid/{customerId}/feature/{some-id}

Service#3, Scenario#1
http://127.0.0.1:8090/Mockey/service/api/v1/cxtid/{contextId}/cid/{customerId}/feature/somefunctionality/subfunctionality

When we make request to Service#1, Scenario#1 the application returns response of Service#2, Scenario#1 or  Service#3, Scenario#1. This happens either URL partially matches or RegExp for path variables matches any sub path

**Comment by clafonta** [comment]
Apologies for the late reply. Thanks for the updates!

**Comment by A-MohanRao** [comment]
Thanks for taking a look at the updates.
