### ISSUE TITLE
Where does war look for service definitions?

### ISSUE THREAD

**Issue by emilesvt** [clafonta/Mockey#78]
Sorry, this is more of a question as I don't see it in the help files.

I have a desire to deploy the Mockey.war programmatically into a jetty container during a Maven build, to leverage for some integration tests.  I'd like to provide those definitions to Mockey, but unsure where Mockey looks for those files by default.  Where is that location and is it configurable via a Servlet parameter or something?

Thanks!

**Comment by cyxop** [comment]
I build Mockey.war and deployed it on Tomcat 7.0.65
I set environment in default.properties file:

user.dir=/Users/MockeyTest
pathToMockeyDebugFile=/Users/MockeyTest/logs

However, it cannot find mock_service_definitions.xml file.



However, it cannot find

**Comment by clafonta** [comment]
I fixed the build problem. The challenge was inclusion of compiled JSPs for Jetty but running in Tomcat. There's a new Ant build target called 'webapptomcat'. 

Specific to looking to an environment variable, to explicitly set the location of your Mockey definitions-repot, I'll have to set that up, something like: http://stackoverflow.com/questions/17019233/pass-user-defined-environment-variable-to-tomcat

I'll get to that tomorrow.

**Comment by clafonta** [comment]
Apologies for keeping this open so long. Before you start, Tomcat/Jetty (using .war file), be sure to setup JAVA_OPTS. For example: 

`export JAVA_OPTS="-DmockeyDefinitionsRepoHome=/Users/yourusername/tmp"`

Then start Tomcat. 

For the executable Mockey.jar file that contains Jetty, then run the following: 

`java -jar Mockey.jar -l /Users/yourusername/tmp`
