### ISSUE TITLE
Not setting tags causes an exception when filtering history by tags

### ISSUE THREAD

**Issue by joshnhickman** [clafonta/Mockey#84]
If there are no tags set for a given scenario in the history and com.mockey.storage.InMemoryMockeyStorage.getFulfilledClientRequest(filterArguments) is called, a NullPointerException is thrown due to getScenarioTagsAsString() returning null, which prevents any history from being returned.

**Comment by clafonta** [comment]
I couldn't reproduce this but I put in some 'null' checks based on your comments. Re-open if this doesn't fix it.
