### ISSUE TITLE
Scenarios returned as a "Service Scenario Error Response" do not send Headers.

### ISSUE THREAD

**Issue by joshnhickman** [clafonta/Mockey#87]
I've created a number of Scenarios for a given Service, with one marked as the "Service Scenario Error Response." However, when the error Scenario is returned due to no other scenarios matching, the headers are not included.

This does not happen when the same scenario (still marked as the error response) is returned due to matching the match arguments, only when it is returned as the error response.

**Comment by clafonta** [comment]
Howdy Josh - I'll look into this on the weekend. Thanks for the insight.
