### ISSUE TITLE
Special characters/encoding support

### ISSUE THREAD

**Issue by fernandospr** [clafonta/Mockey#90]
I am trying to put a response content with special characters:
For example:
```
{
   "id":"Mi id",
   "description": "Una descripción"
}
```

However when I use the mocked service I see:
```
{
   "id":"Mi id",
   "description": "Una descripciÃ³n"
}
```
Please, can you add support for this?

**Comment by clafonta** [comment]
Thanks for raising the issue.  Fixed.

**Comment by fernandospr** [comment]
Thank you!!

![Image of Mickey](http://vignette2.wikia.nocookie.net/doblaje/images/3/3a/Mickey_mouse-1097.jpg/revision/latest?cb=20130925015641&path-prefix=es)

**Comment by fernandospr** [comment]
@clafonta Sorry, can you reopen the issue?

I have noticed that it is not working as expected.
Using ```curl``` I am not getting the special characters, instead I get diamonds:

```
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Content-Type: application/json; charset=UTF-8
< Transfer-Encoding: chunked
< Server: Jetty(2.0.73)
<
{
   "id":"Mi id",
   "description": "Una descripci�n"
}
```

**Comment by clafonta** [comment]
You'll need to curl to accept the encoding. For more, see: 
http://stackoverflow.com/questions/10172327/linux-curl-save-as-utf-8

**Comment by fernandospr** [comment]
Thanks for your response, but I think that is not the problem, I'm executing:

```
curl -v -H "Accept-Charset: UTF-8;" -H "Accept: application/json" http://myservice/url
```

**Comment by fernandospr** [comment]
Anyway, calling the real service with curl does not need any headers and it will return the special characters. So I guess the issue must be somewhere else.

**Comment by clafonta** [comment]
Here's what I did: 

`curl http://127.0.0.1:8080/service/service1
{
   "id":"Mi id",
   "description": "Una descripci?n"
}
`
...but this is what I get with accept headers:

`curl -H "Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7" http://127.0.0.1:8080/service/service1 | iconv -f iso8859-1 -t utf-8 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    57    0    57    0     0  16579      0 --:--:-- --:--:-- --:--:-- 19000
{
   "id":"Mi id",
   "description": "Una descripción"
}
`

**Comment by fernandospr** [comment]
Ok that works, but you are converting the output of curl from iso8859-1 to utf-8 using iconv.
I think the service should already return the JSON in utf-8.

Using curl was just an example, I'm using other clients (e.g. Android/iOS) and I have the same problem. I'm not having this issue with the real service. 

I think it should not be needed to manually convert iso8859-1 to utf-8.

**Comment by clafonta** [comment]
OK. Within Mockey, you can update the content-type per scenario.  Try updating the scenario with this:

Content-Type: text/html; charset=utf-8 

![screen shot 2016-07-01 at 1 23 28 pm](https://cloud.githubusercontent.com/assets/54388/16533665/493b7ba8-3f8f-11e6-85a1-84f703915894.png)

..and see if that works.

**Comment by fernandospr** [comment]
Thanks. I have already tried that, but it didn't work.

**Comment by clafonta** [comment]
Apologies for this. Things worked running on Tomcat by not Jetty. I think I fixed it now. 

![screen shot 2016-07-02 at 8 05 35 am](https://cloud.githubusercontent.com/assets/54388/16541018/3fe736b6-402d-11e6-895b-ed7b65953f7e.png)
![screen shot 2016-07-02 at 8 06 10 am](https://cloud.githubusercontent.com/assets/54388/16541020/449f97e8-402d-11e6-8441-875bf8cb9446.png)

**Comment by fernandospr** [comment]
Thanks! It is working now ;)
