### ISSUE TITLE
utf8 problem

### ISSUE THREAD

**Issue by kaisaint** [clafonta/Mockey#91]
I'm use tomcat to deploy the mockey.war，and my encode is utf-8，i have set the tomcat server.xml URIEncoding="UTF-8"，but when i add a mock service,when i add the Scenario Response Content,it contains chinese，like "中文",when i update the Scenario and reopen it, the Scenario Response Content “中文”  become ??

**Comment by clafonta** [comment]
Thanks for bringing up the issue. Fixed (I believe). Let me know if not, and I'll open and revisit. Also,  checkout the Download section for pre-built .jar and .war files. https://github.com/clafonta/Mockey/wiki/Downloads

**Comment by kaisaint** [comment]
thank for your help,it's fixed.by the way,if the project support soap webservice mock?

**Comment by clafonta** [comment]
There's no plan to support full SOAP test creation and management, since [SoapUI](https://www.soapui.org/) does a pretty good job at this. Mockey's purpose is to be a simple front end to writing test-responses to the file system for persistence to git.
