### ISSUE TITLE
Get number of requests serviced in Dashboard

### ISSUE THREAD

**Issue by sukhdeepsinghkohli** [clafonta/Mockey#92]
Hi

First of all, thanks for amazing work

I was wondering if there is a way to show or get the number of requests serviced by a stub "till now" or a timerange ?

**Comment by clafonta** [comment]
There isn't an easy way to do this, but if you give me more details on what you want to have/see, then I may be able to code it.

**Comment by sukhdeepsinghkohli** [comment]
Actually, I am trying to ascertain the throughput the component is able to achieve given Mockey response. 

So basically, lets say...particular transaction was served XX times by mockey in last one hour

**Comment by clafonta** [comment]
See the latest version, 2.0.80. I added a 'History Stats' page with a simple chart and filter, in addition to an export to JSON or CSV for further analysis. Let me know if that works.

**Comment by sukhdeepsinghkohli** [comment]
@clafonta 

1. The Current logs is great....
However, let me add some screenshots from CA DevTest (formerly Lisa) so it is bit easier to understand.

Looking for way to know
- To know the count of total requests served per service
- To further filter no of request served in last "X" time....lets say last 1 hour -> basically throughput

Links of screenshot
http://i.imgur.com/zBsMPU4.png
http://i.imgur.com/La3aKOT.png

**Comment by sukhdeepsinghkohli** [comment]
@clafonta 

Oops! I missed the History Stats page...

1. I only see it is stuck with time...doesn't let you go back more than 2 minutes
2. Even though...it has serviced more than 25 requests, it is stuck at 25 count

**Comment by sukhdeepsinghkohli** [comment]
@clafonta 

Can you check the bugs I submitted earlier ? 

1. Even though...it has serviced more than 25 requests, it is stuck at 25 count
2. it is stuck with time...doesn't let you go back more than 2 minutes

**Comment by sukhdeepsinghkohli** [comment]
@clafonta 

Thanks for making this up but I see the issues gets closed. Is it safe to assume...this issue is closed and won't be fixed ?

**Comment by clafonta** [comment]
OK. I'll re-open and follow up. Kind of busy....will look into it this weekend.

**Comment by clafonta** [comment]
I took another pass at the History Stats page. 
* removed the history cap of 25 records
* the time range can be moved by 'seconds' 
* limited the History page to only display 100 records; otherwise the page won't render, e.g have > 3000 records

Note: I'm not sure what will happen with 1,000,000s of requests since Mockey holds all things in memory.

**Comment by sukhdeepsinghkohli** [comment]
I see....Will it not work if I run a performance test with 1000 hits per second against it ?

**Comment by clafonta** [comment]
It should. Closing now...will re-open if there are issues.
