### ISSUE TITLE
Enable hang time on scenario level

### ISSUE THREAD

**Issue by yongtao2** [clafonta/Mockey#99]
In current Mockey, we can only enable/edit the hang time on service level.  Could you make the hang time on scenario level?  Please let us know the possibility to have this feature. We have Mockey in our CI/DC pipeline. We hope to use it more.  Thanks.

**Comment by clafonta** [comment]
It's possible but I'll need a little more information. Give me a user story, e.g., "As a user, I want to...." etc.

**Comment by yongtao2** [comment]
As a developer, I want to use Selenium or similar tool to test our UI application not only on normal use cases, but also want test how the ui app handles timeout or slow response cases from other dependent services, which are on different data centers or internet. Those services were Mockeyed for the testing on more than just timeout cases. We want each mockeyed service can have long hang time on some of its test scenarios for the timeout test cases.  
We could do the timeout tests with current Mockey, by setting up another UI app instance to point to another Mockey instance that has long hang-time services dedicated for this type of testing. This approach is taking too much resources and harder to maintain.

**Comment by clafonta** [comment]
The hangtime attribute has been added to the Scenario.

**Comment by yongtao2** [comment]
Thank you very much! You are appreciated.
We will try to use the new feature as soon as we can.
